In [87]:
import pandas as pd
import seaborn as sns
import matplotlib as plt
import numpy as np

In [88]:
df = pd.read_csv('Titanic dataset.csv')

In [89]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [90]:
df.shape

(891, 12)

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [92]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [93]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [94]:
df.duplicated().sum()

0

In [95]:
columns_to_remove = ['PassengerId', 'Name', 'Ticket', 'Cabin']

In [96]:
df.drop(columns=columns_to_remove, inplace=True)

In [97]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [98]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']), df['Survived'], test_size=0.2)

In [99]:
X_train

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
442       3    male  25.0      1      0    7.7750        S
687       3    male  19.0      0      0   10.1708        S
166       1  female   NaN      0      1   55.0000        S
343       2    male  25.0      0      0   13.0000        S
713       3    male  29.0      0      0    9.4833        S
..      ...     ...   ...    ...    ...       ...      ...
329       1  female  16.0      0      1   57.9792        C
550       1    male  17.0      0      2  110.8833        C
321       3    male  27.0      0      0    7.8958        S
415       3  female   NaN      0      0    8.0500        S
576       2  female  34.0      0      0   13.0000        S

[712 rows x 7 columns]

In [100]:
y_train

442    0
687    0
166    1
343    0
713    0
      ..
329    1
550    1
321    0
415    0
576    1
Name: Survived, Length: 712, dtype: int64

In [101]:
from sklearn.impute import SimpleImputer
si_embarked = SimpleImputer(strategy='most_frequent')
si_age = SimpleImputer()

X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])

X_test_age = si_age.transform(X_test[['Age']])
X_test_embarked = si_embarked.transform(X_test[['Embarked']])

In [102]:
np.isnan(X_train_age)

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [103]:
from sklearn.preprocessing import OneHotEncoder
ohe_embarked = OneHotEncoder(sparse=False, handle_unknown='ignore')
ohe_sex = OneHotEncoder(sparse=False, handle_unknown='ignore')

X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)
X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])

X_test_embarked = ohe_embarked.transform(X_test_embarked)
X_test_sex = ohe_sex.transform(X_test[['Sex']])

C:\Users\masan\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\masan\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [104]:
X_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [105]:
X_train_sex

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [106]:
from sklearn.preprocessing import StandardScaler
sc_age = StandardScaler()
sc_fare = StandardScaler()

sc_age.fit(X_train[['Age']])
sc_fare.fit(X_train[['Fare']])

X_train_age = sc_age.transform(X_train_age)
X_train_fare = sc_fare.transform(X_train[['Fare']])

X_test_age = sc_age.transform(X_test_age)
X_test_fare = sc_fare.transform(X_test[['Fare']])

C:\Users\masan\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\masan\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [107]:
X_train_rem = X_train.drop(columns=['Sex', 'Age', 'Fare', 'Embarked'])
X_test_rem = X_test.drop(columns=['Sex', 'Age', 'Fare', 'Embarked'])

In [108]:
X_train_transformed = np.concatenate((X_train_rem, X_train_sex, X_train_embarked, X_train_age, X_train_fare), axis=1)
X_test_transformed = np.concatenate((X_test_rem, X_test_sex, X_test_embarked, X_test_age, X_test_fare), axis=1)

In [109]:
X_train_transformed

array([[ 3.        ,  1.        ,  0.        , ...,  1.        ,
        -0.30975968, -0.50074824],
       [ 3.        ,  0.        ,  0.        , ...,  1.        ,
        -0.72602717, -0.45175752],
       [ 1.        ,  0.        ,  1.        , ...,  1.        ,
         0.        ,  0.4649362 ],
       ...,
       [ 3.        ,  0.        ,  0.        , ...,  1.        ,
        -0.17100385, -0.49827806],
       [ 3.        ,  0.        ,  0.        , ...,  1.        ,
         0.        , -0.49512488],
       [ 2.        ,  0.        ,  0.        , ...,  1.        ,
         0.31464156, -0.39390439]])

In [110]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train_transformed, y_train)

LogisticRegression()

In [114]:
 y_pred = lr.predict(X_test_transformed)

In [115]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8100558659217877

In [116]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(X_train_transformed, y_train)

DecisionTreeClassifier()

In [117]:
 y_pred = dtc.predict(X_test_transformed)

In [118]:
accuracy_score(y_test, y_pred)

0.7988826815642458

In [119]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train_transformed, y_train)

RandomForestClassifier()

In [121]:
 y_pred = rfc.predict(X_test_transformed)

In [122]:
accuracy_score(y_test, y_pred)

0.8100558659217877

In [123]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train_transformed, y_train)

SVC()

In [124]:
y_pred = svc.predict(X_test_transformed)